import { identity } from './identity.js';

export async function introspectColumns(client, schemas) {
  const result = await client.query(`
    select
      n.nspname as schema_name,
      c.relname as table_name,
      a.attname as column_name,
      pg_catalog.format_type(a.atttypid, a.atttypmod) as data_type,
      a.attnotnull as not_null,
      pg_catalog.pg_get_expr(d.adbin, d.adrelid) as "default",
      a.attidentity as identity_type,
      a.attgenerated as generated,
      case when a.attcollation <> 0 and a.attcollation <> (
        select typcollation from pg_catalog.pg_type where oid = a.atttypid
      ) then co.collname else null end as collation,
      a.attnum as position
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    left join pg_catalog.pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    left join pg_catalog.pg_collation co on co.oid = a.attcollation
    where n.nspname = any($1)
      and c.relkind in ('r', 'p')
      and a.attnum > 0
      and not a.attisdropped
    order by n.nspname, c.relname, a.attnum
  `, [schemas]);

  return result.rows.map(row => {
    const qualifiedName = `${row.table_name}.${row.column_name}`;

    let ddlCreate = `alter table ${qualify(row.schema_name, row.table_name)} add column ${quote(row.column_name)} ${row.data_type}`;
    if (row.collation) {
      ddlCreate += ` collate "${row.collation}"`;
    }
    if (row.not_null) {
      ddlCreate += ' not null';
    }
    if (row.default && !row.identity_type && !row.generated) {
      ddlCreate += ` default ${row.default}`;
    }
    if (row.identity_type === 'a') {
      ddlCreate += ' generated always as identity';
    } else if (row.identity_type === 'd') {
      ddlCreate += ' generated by default as identity';
    }
    if (row.generated === 's') {
      ddlCreate += ` generated always as (${row.default}) stored`;
    }
    ddlCreate += ';';

    return {
      identity: identity(row.schema_name, 'column', qualifiedName),
      definition: {
        name: row.column_name,
        table: row.table_name,
        schema: row.schema_name,
        data_type: row.data_type,
        not_null: row.not_null,
        default: row.default,
        identity: row.identity_type || null,
        generated: row.generated || null,
        collation: row.collation,
        position: row.position,
      },
      ddl: {
        create: ddlCreate,
        // drop: `alter table ${qualify(row.schema_name, row.table_name)} drop column ${quote(row.column_name)};`,
        alter: (fromDef, toDef) => {
          const stmts = [];
          const tbl = qualify(toDef.schema, toDef.table);
          const col = quote(toDef.name);
          if (fromDef.data_type !== toDef.data_type) {
            stmts.push(`alter table ${tbl} alter column ${col} set data type ${toDef.data_type} using ${col}::${toDef.data_type};`);
          }
          if (fromDef.not_null !== toDef.not_null) {
            stmts.push(`alter table ${tbl} alter column ${col} ${toDef.not_null ? 'set' : 'drop'} not null;`);
          }
          if (fromDef.default !== toDef.default) {
            if (toDef.default) {
              stmts.push(`alter table ${tbl} alter column ${col} set default ${toDef.default};`);
            } else {
              stmts.push(`alter table ${tbl} alter column ${col} drop default;`);
            }
          }
          return stmts.join('\n');
        },
      },
    };
  });
}

function quote(name) {
  if (/^[a-z_][a-z0-9_]*$/.test(name)) return name;
  return `"${name}"`;
}

function qualify(schema, name) {
  return `${quote(schema)}.${quote(name)}`;
}
